###GET
GET http://localhost:8000/todos

###POST
POST http://localhost:8000/todos
Content-Type: application/json

{
    "description" : "Test",
    "user_id" : 1,
    "family_id" : 1
} 

###PUT
PUT http://localhost:8000/todos/1
Content-Type: application/json

{
    "description": "Prendre RDV pour chloé"
}

###DELETE
DELETE http://localhost:8000/todos/1
